language: ruby
rvm:
  - 2.1.4
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database demo_voltmobi_test;' -U postgres

